config/routes.rb
Rails.application.routes.draw do
    root 'top#main'
    get 'top/main'
    resources :products
    resources :cart_items,only: [:create,:destroy]
    resources :carts,only: [:show]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
end

app/models/cartitem.rb
class Cartitem < ApplicationRecord
end

app/models/product.rb
class Product < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    private
    def current_cart
        if session[:cart_id]
            cart = Cart.find(session[:cart_id])
        else
            cart = Cart.create
            session[:cart_id] = cart.id
        end
        cart
    end
    helper_method :current_cart
end

app/controllers/cart_items_controller.rb
class CartItemsController < ApplicationController
    def create
        @cart_item = Cartitem.new(qty: params[:qty],
            product_id: params[:product_id],
            cart_id: current_cart.id
            )
        if @cart_item.save
          redirect_to top_main_path
        else
          render top_main_path
        end
    end
    
    def destroy
        cart_item = Cartitem.where(params[:product_id])
        cart_item.destroy_all
        redirect_to top_main_path
    end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
    def show
        @cart = Cart.all
        @products = Product.all
        @cartitems = Cartitem.all
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
    def index
        @products = Product.all
    end
    
    def new
        @product = Product.new
    end
    
    def create
        @product = Product.new(name: params[:product][:name], price: params[:product][:price])
        if @product.save
          redirect_to products_path
        else
          render new_product_path
        end
    end
    
    def destroy
        product = Product.find(params[:id])
        product.destroy
        redirect_to products_path
    end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
    def main
        @products = Product.all
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/views/carts/show.html.erb
<% sum = 0 %>
<% @cartitems.each do |c| %>
<p>
    <% p = @products.find_by(id: c.product_id) %>
    名前：<%= p.name %>
    価格：<%= p.price %>
    量：<%= c.qty %>
    <% sum += p.price * c.qty%>
</p>
<% end %>
<p>合計金額：<%= sum %>円</p>
<p><%= link_to '戻る', :back %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>L6</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/products/index.html.erb
<% if flash[:info] %>
<%= flash[:info] %>
<% end %>

<% @products.each do |e| %>
<p>
  商品名：<%= e.name %>
  価格：<%= e.price %>
  <%= link_to '削除', product_path(e), method: :delete %>
</p>
<% end %>

<p><%= link_to '商品登録', new_product_path %></p>

<p><%= link_to '戻る', top_main_path %></p>

app/views/products/new.html.erb
<%= form_for @product, url: {action: :create} do |f| %>
<p>
  <%= f.label :name, '商品名' %>
  <%= f.text_field :name %>
</p>
<p>
  <%= f.label :price, '値段' %>
  <%= f.text_field :price %>
</p>
<p>
  <%= f.submit '登録' %>
</p>
<% end %>

<p><%= link_to '戻る', :back %>

app/views/top/main.html.erb
<% if flash[:info] %>
  <%= flash[:info] %>
<% end %>
<h1>o-zon</h1>
<h2>商品一覧</h2>
<% @products.each do |e| %>
<p>
  <%= form_tag cart_items_path,method: :post do %>
  商品名：<%= e.name %>
  価格：<%= e.price %>
  <%= hidden_field_tag :product_id,e.id %>
  数量：<%= select_tag(:qty,options_for_select((1..30))) %>
  <%= submit_tag 'カートへ追加'%>
  <%= link_to 'この商品をカートから削除', cart_item_path(e), method: :delete %>
  <% end %>
  <hr>
</p>
<% end %>
<p><%= link_to 'カート', cart_path(current_cart.id) %></p>

<p><%= link_to '商品登録', products_path %></p>